appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: B0cgqFlmfVmnTid19/KJt21KnZLHQAEYRrjEvOq48kuKknr71jAXHGpAmp+nZ/h1DAeWBxJUUdp+vczKfi+XvWk2P/ZALUn3tlSmB3uLRd/ZbvHAu7f63o5e//WJxgPX33nDC2AbZHSJUYcC111ch65Cyzh1E/p3KLGYR8uZ0LbgryG+aMv6CVtpOHIK156diEu3RI3b0TvGZPiIKcgq/K3XjrBvmhQ3uV7tOiXznmkz7j81wdt2I8mYR/yLex9z9jlZC1jG/wiDOz86ItL5TqmS6PqHD+rKOAjiSDxQwSLx6/d/3pRjK7VrVcvdwuztOdYLA615muCATVCk/n0rSjEl1jff7JljMQMbysYkGG/nE+ieBKT3ITsXTLN6jvMSR4RmrfIj0LhHNyNIAgQuOQ7pgyizNtosDRR0dU0KZ31vGA7ycpPMMBcSOspSS/9x1C5pTzYF8HSOOSWekhpFLSiUEfkHPcpo5TFRs7kgk1tMnijjIDTlnq1SYqRwOXBXykqrajUjYJCPNV8EhWzzjFFfwhCOrT2/+/dUVNttpH8okQJq6Li+rpFuVgQuY1mrLgN0ttJV5L2In/P5RBV6migBlniFznzF4RI4xigBbRXyCC4dg5cHbf66jrYaYq9QWlJ9ASbMlWUWlx0hMkQrpxUwL5nUsuNnOHoVkbmSIdE=}
