travis:
  secure:
    BINSTAR_TOKEN: LjS/u++7e05q9Mu1jh+RmRdznYHnrCaAyVb5DJcXYb89EQG1gkRtmpVhm9sFK4MMAid+R8NBKU1nBujjlAdyV523fCi3vFH0SilMb6hDzLOHSPBPXdiQIQDDqA2Dwn2TfcMprPmEMVUNZ8Z+qFjuVwxFLnj0AFkp3/83L/Dpy77Ozicv1hgojR7UfF3Hd+FpM7aEeWNm3GDyQYXVKxggv1H3sRdO/SooC1uEMQTVB+YLSexZlw2TFxmBw9b2gAaVE/cwZJukdxc5wk57TiVrZUVuYDUR0x3HP9NrdFNho+Pv+4c+oCFPDhbkL5GQNU2wK1zEaAKPWanYnpF72YjBHDsrEmt1HxUnp2XG3VIoqH7F4QY148rw1SWUHcUx0u3EH2kQMs2cJiPPl51JJQAfrx0RVDEuowMC/vALHoUYZ2wNfQNQFuWkJ3Y6RWAUlNzNaSO0dG7AYRzblR1HywYMww1XuEOZFVBPJyzOQlt+ak/drmpq/1aj+tm21tENv3E/YamVzg3+/q66ivll/0dJVKvUU2SdG7LwzPLaYhvUCI1/Yscje458T1d2WCtGXHdVddIepd3/GgYfsCbW5OohRomxPyo0dOTPf84Fc6ETCX3MOxRW5qJahOgN+D4ITJLsaTKm2js4Hxz5ViMhYNovd6OCE5tauEs0PqrCNEW1JTQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
